### ISSUE TITLE
block-fake-pdf-sites listesi için dosya yolu değişmiş

### ISSUE THREAD

**Issue by melisa-malvina** [HuzunluArtemis/TurkishAdblockList#2]
güncel yol: https://gitlab.com/anarcho-copy/block-fake-pdf-sites/-/raw/master/output/hosts
eski yol: https://gitlab.com/anarcho-copy/block-fake-pdf-sites/-/raw/master/hosts

**Comment by HuzunluArtemis** [comment]
teşekkürler güncelleyeyim
